import { Box, Button, Center, Group, TextInput } from '@mantine/core';
import { useForm } from '@mantine/form';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

const allowedUsers: { username: string; password: string }[] = [
  {
    username: 'admin',
    password: 'admin',
  },
  {
    username: 'ahmet',
    password: 'ahmet',
  },
];

export default function Home() {
  const router = useRouter();

  const form = useForm({
    mode: 'uncontrolled',
    initialValues: {
      username: '',
      password: '',
    },

    validate: {
      username: (val) => val.length <= 0 && 'Username is required',
      password: (val) => val.length <= 0 && 'Password is required',
    },
  });

  const isValidUser = (values: (typeof form)['values']): boolean => {
    return Boolean(
      allowedUsers.find(
        (user) =>
          user.username === values.username && user.password === values.password
      )
    );
  };

  React.useEffect(() => {
    if (localStorage.getItem('user')) {
      router.push('/dashboard');
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>BLM2042 Project</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>
        <Center w="100%" h="100vh">
          <Box
            w={300}
            px="lg"
            component="form"
            onSubmit={form.onSubmit((values) => {
              if (isValidUser(values)) {
                router.push('/dashboard');
                localStorage.setItem('user', values.username);
              }
            })}
          >
            <TextInput
              withAsterisk
              label="Username"
              placeholder="your username"
              key={form.key('username')}
              {...form.getInputProps('username')}
            />

            <TextInput
              pt="sm"
              withAsterisk
              label="Password"
              placeholder="your password"
              key={form.key('password')}
              {...form.getInputProps('password')}
            />

            <Group pt="md">
              <Button variant="light" color="indigo" fullWidth type="submit">
                Login
              </Button>
            </Group>
          </Box>
        </Center>
      </main>
    </>
  );
}
