import { AppShell, Group, Burger, Skeleton } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconBrandMantine } from '@tabler/icons-react';
import Head from 'next/head';

import { api } from '~/utils/api';

export default function Home() {
  const hello = api.post.hello.useQuery({ text: 'from tRPC' });
  const [opened, { toggle }] = useDisclosure();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell
          header={{ height: 60 }}
          navbar={{
            width: 300,
            breakpoint: 'sm',
            collapsed: { mobile: !opened },
          }}
          padding="md"
        >
          <AppShell.Header>
            <Group h="100%" px="md">
              <Burger
                opened={opened}
                onClick={toggle}
                hiddenFrom="sm"
                size="sm"
              />
              <IconBrandMantine
                size={30}
                stroke={1.5}
                color="var(--mantine-color-blue-filled)"
              />
            </Group>
          </AppShell.Header>
          <AppShell.Navbar p="md">
            Navbar
            {Array(15)
              .fill(0)
              .map((_, index) => (
                <Skeleton key={index} h={28} mt="sm" animate={false} />
              ))}
          </AppShell.Navbar>
          <AppShell.Main>Main</AppShell.Main>
        </AppShell>
      </main>
    </>
  );
}
