import {
  AppShell,
  Group,
  Burger,
  NavLink,
  Space,
  Text,
  Button,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import {
  IconBrandDatabricks,
  IconBrandMantine,
  IconBuildingFactory2,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconHome,
  IconTir,
} from '@tabler/icons-react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import type { FormEvent, PropsWithChildren } from 'react';
import React, { useState } from 'react';

export default function DashboardLayout({ children }: PropsWithChildren) {
  const router = useRouter();
  const [opened, { toggle }] = useDisclosure();
  const [user, setUser] = useState('');

  const onClick = () => {
    localStorage.setItem('user', '');
    setUser('');
    router.push('/');
  };

  React.useEffect(() => {
    const user = localStorage.getItem('user');
    if (!user) router.push('/');
    else setUser(user);
  }, [router]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell
          header={{ height: 60 }}
          navbar={{
            width: 300,
            breakpoint: 'sm',
            collapsed: { mobile: !opened },
          }}
          padding="md"
        >
          <AppShell.Header>
            <Group justify="space-between" h="100%" px="md">
              <Group>
                <Burger
                  opened={opened}
                  onClick={toggle}
                  hiddenFrom="sm"
                  size="sm"
                />
                <IconBrandMantine
                  size={30}
                  stroke={1.5}
                  color="var(--mantine-color-blue-filled)"
                />
                <Text>{user.toUpperCase()}</Text>
              </Group>

              <Button onClick={onClick} color="red" variant="light">
                Log out
              </Button>
            </Group>
          </AppShell.Header>
          <AppShell.Navbar p="sm">
            <NavLink
              style={{ borderRadius: 6 }}
              component={Link}
              href="/dashboard"
              label="Home"
              leftSection={<IconHome size="1.2rem" stroke={2} />}
              active={router.pathname === '/dashboard'}
            />
            <Space h="xs" />
            <NavLink
              style={{ borderRadius: 6 }}
              component={Link}
              href="/dashboard/orders"
              label="Orders"
              leftSection={<IconBuildingStore size="1.2rem" stroke={2} />}
              active={router.pathname === '/dashboard/orders'}
            />
            <Space h="xs" />
            <NavLink
              style={{ borderRadius: 6 }}
              component={Link}
              href="/dashboard/materials"
              label="Materials"
              leftSection={<IconBuildingWarehouse size="1.2rem" stroke={2} />}
              active={router.pathname === '/dashboard/materials'}
            />
            <Space h="xs" />
            <NavLink
              style={{ borderRadius: 6 }}
              component={Link}
              href="/dashboard/stock"
              label="Stock"
              leftSection={<IconBrandDatabricks size="1.2rem" stroke={2} />}
              active={router.pathname === '/dashboard/stock'}
            />
            <Space h="xs" />
            <NavLink
              style={{ borderRadius: 6 }}
              component={Link}
              href="/dashboard/workshop"
              label="Workshop"
              leftSection={<IconBuildingFactory2 size="1.2rem" stroke={2} />}
              active={router.pathname === '/dashboard/workshop'}
            />
            <Space h="xs" />
            <NavLink
              style={{ borderRadius: 6 }}
              component={Link}
              href="/dashboard/logistic"
              label="Logistic"
              leftSection={<IconTir size="1.2rem" stroke={2} />}
              active={router.pathname === '/dashboard/logistic'}
            />
          </AppShell.Navbar>
          <AppShell.Main>{children}</AppShell.Main>
        </AppShell>
      </main>
    </>
  );
}
